/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * LlaveDEs.java
 *
 * Created on Nov 22, 2009, 8:39:03 PM
 */

package Interfaz;

import Utilidades.Conversores;
import javax.swing.ComboBoxModel;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;

/**
 *
 * @author Mercurio
 */
public class LlaveAES extends javax.swing.JDialog {
 private static final  int LLAVE_128_BITS=1;
 private static final  int LLAVE_192_BITS=2;
 private static final  int LLAVE_256_BITS=3;
 private String hexkey=null;
 private int hexleng=0;
 private int tipo_llave;
 private Object[] llavestam={"128 bits","192 bits","256 bits"};
 private DefaultComboBoxModel comb=new DefaultComboBoxModel(llavestam);
    public String getHexkey() {
        return hexkey;
    }
    private int getTipoLlave(String llavetxt){
        int llave=0;
        if(llavetxt.equals(llavestam[0])){
            llave= LLAVE_128_BITS;
        }
        if(llavetxt.equals(llavestam[1])){
           llave= LLAVE_192_BITS;
        }
        if(llavetxt.equals(llavestam[2])){
            llave= LLAVE_256_BITS;
        }
        return llave;
    }
    private int getHexLenght(int llaveleng){
        int result=0;
        if(llaveleng==LLAVE_128_BITS){
            result=32;
        }
        if(llaveleng==LLAVE_192_BITS){
            result=48;
        }
        if(llaveleng==LLAVE_256_BITS){
            result=64;
        }
        return result;
    }
    public void setHexkey(String hexkey) {
        this.hexkey = hexkey;
    }
    /** Creates new form LlaveDEs */
    public LlaveAES(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        iniciar();
    }
    private void iniciar(){
        tam_llave_cb.setModel(comb);
        tam_llave_cb.setSelectedIndex(0);
    }
    private boolean valida(int tam_llave,String hexcadllave){
        boolean bande=false;
        if(tam_llave==LLAVE_128_BITS){
            if(hexcadllave.length()==32){
                bande=true;
            }
        }
        if(tam_llave==LLAVE_192_BITS){
            if(hexcadllave.length()==48){
                bande=true;
            }
        }
        if(tam_llave==LLAVE_256_BITS){
            if(hexcadllave.length()==64){
                bande=true;
            }
        }
        return bande;
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLayeredPane1 = new javax.swing.JLayeredPane();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        key_ascii_txt = new javax.swing.JTextField();
        hex_key_txt = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        bin_key_txt = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        octal_txt = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        acept_bt = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        tam_llave_cb = new javax.swing.JComboBox();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Llave de Cifrado...");

        jLayeredPane1.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createTitledBorder("Llave")));

        jLabel1.setText("ASCCII:");
        jLabel1.setBounds(20, 20, 60, 15);
        jLayeredPane1.add(jLabel1, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jLabel2.setText("BINARIO:");
        jLabel2.setBounds(20, 100, 55, 15);
        jLayeredPane1.add(jLabel2, javax.swing.JLayeredPane.DEFAULT_LAYER);

        key_ascii_txt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                key_ascii_txtActionPerformed(evt);
            }
        });
        key_ascii_txt.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                key_ascii_txtKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                key_ascii_txtKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                key_ascii_txtKeyTyped(evt);
            }
        });
        key_ascii_txt.setBounds(120, 20, 250, 19);
        jLayeredPane1.add(key_ascii_txt, javax.swing.JLayeredPane.DEFAULT_LAYER);

        hex_key_txt.setToolTipText("");
        hex_key_txt.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                hex_key_txtKeyReleased(evt);
            }
        });
        hex_key_txt.setBounds(120, 60, 250, 19);
        jLayeredPane1.add(hex_key_txt, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jLabel3.setText("HEXADECIMAL:");
        jLabel3.setBounds(20, 60, 93, 15);
        jLayeredPane1.add(jLabel3, javax.swing.JLayeredPane.DEFAULT_LAYER);

        bin_key_txt.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                bin_key_txtMouseReleased(evt);
            }
        });
        bin_key_txt.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                bin_key_txtKeyReleased(evt);
            }
        });
        bin_key_txt.setBounds(120, 100, 250, 19);
        jLayeredPane1.add(bin_key_txt, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jLabel4.setText("OCTAL:");
        jLabel4.setBounds(20, 130, 46, 15);
        jLayeredPane1.add(jLabel4, javax.swing.JLayeredPane.DEFAULT_LAYER);
        octal_txt.setBounds(120, 130, 250, 19);
        jLayeredPane1.add(octal_txt, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jButton1.setText("Cancelar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        acept_bt.setText("Aceptar");
        acept_bt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                acept_btActionPerformed(evt);
            }
        });

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Tamaño Llave"));

        tam_llave_cb.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "128 bits", "192 bits", "254 bits" }));
        tam_llave_cb.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tam_llave_cbActionPerformed(evt);
            }
        });

        jLabel5.setText("Tamaño:");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel5)
                .addGap(53, 53, 53)
                .addComponent(tam_llave_cb, javax.swing.GroupLayout.PREFERRED_SIZE, 244, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(24, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(tam_llave_cb, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(20, Short.MAX_VALUE))
        );

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/keys.png"))); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(36, 36, 36)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLayeredPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 396, Short.MAX_VALUE)
                            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(33, 33, 33)
                        .addComponent(jLabel6))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap(355, Short.MAX_VALUE)
                        .addComponent(acept_bt, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLayeredPane1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(92, 92, 92)
                        .addComponent(jLabel6)))
                .addGap(46, 46, 46)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(acept_bt, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(13, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void key_ascii_txtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_key_ascii_txtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_key_ascii_txtActionPerformed

    private void key_ascii_txtKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_key_ascii_txtKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_key_ascii_txtKeyPressed

    private void key_ascii_txtKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_key_ascii_txtKeyReleased
        // TODO add your handling code here:
          hex_key_txt.setText(Conversores.assciitoHEX(key_ascii_txt.getText()));
          bin_key_txt.setText(Conversores.assciitoBin(key_ascii_txt.getText()));
          octal_txt.setText(Conversores.assciitoOctal(key_ascii_txt.getText()));
}//GEN-LAST:event_key_ascii_txtKeyReleased

    private void key_ascii_txtKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_key_ascii_txtKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_key_ascii_txtKeyTyped

    private void hex_key_txtKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_hex_key_txtKeyReleased
        // TODO add your handling code here:
          String temp1=Conversores.hextToASSCII(hex_key_txt.getText());
          key_ascii_txt.setText(temp1);          
          bin_key_txt.setText(Conversores.assciitoBin(temp1));
          octal_txt.setText(Conversores.assciitoOctal(temp1));
}//GEN-LAST:event_hex_key_txtKeyReleased

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        setHexkey(null);
        this.dispose();
}//GEN-LAST:event_jButton1ActionPerformed

    private void acept_btActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_acept_btActionPerformed
        // TODO add your handling code here:
        if(hexleng==hex_key_txt.getText().length()){
            setHexkey(hex_key_txt.getText().toUpperCase());
            this.setVisible(false);
        }else{
            JOptionPane.showMessageDialog(null, "La llave debe de ser de "+tam_llave_cb.getSelectedItem().toString());
        }
}//GEN-LAST:event_acept_btActionPerformed

    private void tam_llave_cbActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tam_llave_cbActionPerformed
        // TODO add your handling code here:
        tipo_llave=getTipoLlave(tam_llave_cb.getSelectedItem().toString());
        hexleng=getHexLenght(tipo_llave);
        System.out.println("llave:"+tipo_llave+" l "+hexleng);
    }//GEN-LAST:event_tam_llave_cbActionPerformed

    private void bin_key_txtMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bin_key_txtMouseReleased
        // TODO add your handling code here:
          
    }//GEN-LAST:event_bin_key_txtMouseReleased

    private void bin_key_txtKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_bin_key_txtKeyReleased
        // TODO add your handling code here:
          String temp1=Conversores.binToASSCII(bin_key_txt.getText());
          key_ascii_txt.setText(temp1);
          hex_key_txt.setText(Conversores.assciitoHEX(temp1));
          octal_txt.setText(Conversores.assciitoOctal(temp1));
    }//GEN-LAST:event_bin_key_txtKeyReleased

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                LlaveAES dialog = new LlaveAES(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton acept_bt;
    private javax.swing.JTextField bin_key_txt;
    private javax.swing.JTextField hex_key_txt;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLayeredPane jLayeredPane1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField key_ascii_txt;
    private javax.swing.JTextField octal_txt;
    private javax.swing.JComboBox tam_llave_cb;
    // End of variables declaration//GEN-END:variables

}
